line-length = 100

target-version = "py310"

select = [
    "F",
    "E",
    "W",
    "E",
    "W",
    "C90",
    "I",
    "N",
    "D",
    "UP",
    "YTT",
    "ANN",
    "S",
    "BLE",
    "FBT",
    "B",
    "A",
    "COM",
    "C4",
    "DTZ",
    "T10",
    "DJ",
    "EM",
    "EXE",
    "ISC",
    "ICN",
    "G",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SIM",
    "TID",
    "TCH",
    "INT",
    "ARG",
    "PTH",
    "ERA",
    "PD",
    "PGH",
    "PL",
    "PLC",
    "PLE",
    "PLR",
    "PLW",
    "TRY",
    "NPY",
    "RUF",
]

ignore = [
    'D100',  # Missing docstring in public module
    'D104',  # Missing docstring in public package
    'D203',
    'D212',
]

[per-file-ignores]
"tests/*" = [
    "S101",  # Use of `assert` detected
]

[flake8-quotes]
inline-quotes = 'single'